### ISSUE TITLE
00000072-a-1.json file doesn't have mapped_scores

### ISSUE THREAD

**Issue by EstelleDa** [ave-dcd/dcd_mapping#13]
I downloaded Mapped MaveDB Scoresets files. Only 00000072-a-1.json doesn't have mapped_scores. All of the rest files have.

**Comment by afrubin** [comment]
@jarbesfeld any idea what happened with this one?

**Comment by jarbesfeld** [comment]
@EstelleDa @afrubin We were unable to select a RefSeq protein sequence for this score set (instead UniProt accession P01857 was selected) so were unable to create VRS alleles/haplotypes for the variants in this score set.
